plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = project.mod_version
group = project.mod_group_id

base {
    archivesName = project.archives_base_name
}

sourceSets {
    main {
        java.srcDir("src/client/java")
    }
}

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }

        server {
            server()
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    inputs.property "mod_version", project.mod_version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "minecraft_version_range", project.minecraft_version_range
    inputs.property "neo_version", project.neo_version
    inputs.property "loader_version_range", project.loader_version_range
    inputs.property "mod_id", project.mod_id
    inputs.property "mod_name", project.mod_name
    inputs.property "mod_license", project.mod_license
    filteringCharset "UTF-8"

    filesMatching("META-INF/neoforge.mods.toml") {
        expand(
                "mod_version": project.mod_version,
                "minecraft_version": project.minecraft_version,
                "minecraft_version_range": project.minecraft_version_range,
                "neo_version": project.neo_version,
                "loader_version_range": project.loader_version_range,
                "mod_id": project.mod_id,
                "mod_name": project.mod_name,
                "mod_license": project.mod_license
        )
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE.txt") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {
    }
}
