# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G

# Minecraft / NeoForge
moddevgradle_version=2.0.141
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
neo_version=21.11.42
neo_version_range=[21.11.42,)
loader_version_range=[10.0,)

# Mod Properties
mod_id=better_lost_items
mod_name=Better Lost Items
mod_license=All-Rights-Reserved
mod_version=1.3
maven_group=org.betterLostItems
archives_base_name=better-lost-items
