# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# NeoForge Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.10-beta
loader_version_range=[1,)

# Mod Properties
mod_version=1.2
mod_id=better_lost_items
mod_name=Better Lost Items
mod_license=All Rights Reserved
mod_group_id=org.betterLostItems
archives_base_name=better-lost-items
